name: Build

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4
    - name: Build
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y wget curl git gcc bash gawk gsed
          wget https://dl.google.com/go/go1.22.0.freebsd-amd64.tar.gz && tar -C /usr/local -xzf go1.22.0.freebsd-amd64.tar.gz && rm go1.22.0.freebsd-amd64.tar.gz
          ln -s /usr/local/go/bin/go /usr/local/bin/go
        run: |
          export LATEST_APP=$(wget -qO- https://api.github.com/repos/deanxv/coze-discord-proxy/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          git clone -b $LATEST_APP https://github.com/deanxv/coze-discord-proxy
          cd coze-discord-proxy
          go mod download
          go build -ldflags "-s -w -X 'coze-discord-proxy/common.Version=$(git describe --tags)' -extldflags '-static'" -o coze-discord-proxy
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: coze-discord-proxy-freebsd
        path: |
            coze-discord-proxy/coze-discord-proxy

    - name: Generate release tag
      id: tag
      run: echo "release_tag=$(wget -qO- https://api.github.com/repos/deanxv/coze-discord-proxy/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              coze-discord-proxy/coze-discord-proxy
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
